### ISSUE TITLE
Add Rachel Rose O'Leary

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#137]
Like Amir, we can just copy title and image from HCPP in the immediate term, pending her reply to the actual onboarding.

**Comment by andrewgdick** [comment]
@bobsummerwill she does not have a ranking on the Excel sheet yet.

**Comment by bobsummerwill** [comment]
Thanks!

She just shared this preferred photo with me.

https://www.flickr.com/photos/94861732@N04/52167696243

Preferred title:

DarkFi core dev & writer

**Comment by bobsummerwill** [comment]
Andrew is away.  Please could you do this, Gabriel?  Thanks!

**Comment by bobsummerwill** [comment]
Fixed by https://github.com/POWSummit/pow-summit-website/issues/137
