### ISSUE TITLE
Add Lokotech sponsor at GOLD level (which will need adding)

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#153]
We need to add a new Gold level into the sponsors section and to add Lokotech.

https://www.lokotech.no/

I'll drop the logo into the Telegram group.  I tried imgur upload but it failed.

**Comment by andrewgdick** [comment]
This should be the Logo PNG
![lokotech-logo](https://github.com/POWSummit/pow-summit-website/assets/974129/257e4f57-b994-4818-acd8-39e043a3ea06)

**Comment by bobsummerwill** [comment]
Lokotech is in now, but they need to be in a new Gold tier, not Diamond plus

**Comment by bobsummerwill** [comment]
Done, thanks!
