### ISSUE TITLE
Add Maxim Orlovsky as speaker

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#154]
I have attached his headshot to the Telegram channel.

Name = Maxim Orlovsky
Title = “Prime: new layer 1 for Bitcoin - miner opportunities”

Directly after Igor Barinov, please.

**Comment by andrewgdick** [comment]
@bobsummerwill this is not the same title as the main Excel sheet. Should I use this one?

**Comment by bobsummerwill** [comment]
Oh sorry - that is his speech.

His job title is "LNP/BP Association, engineer of RGB and Prime"
