### ISSUE TITLE
Add iPollo sponsor at Silver level

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#162]
Hyperlink = iPollo.com
Image in Telegram group
Silver level.   Thanks!

**Comment by bobsummerwill** [comment]
So this is using the wrong logo for iPollo.
I will drop a new one in Telegram.

**Comment by bobsummerwill** [comment]
It needs to have a transparent background.

**Comment by andrewgdick** [comment]
![iPollo- Logo and Text- Landscape_Panel 1](https://github.com/POWSummit/pow-summit-website/assets/974129/e7131796-1306-41f6-bf79-aae8f3773a37)

**Comment by bobsummerwill** [comment]
Done, thanks!
