### ISSUE TITLE
Add Ballet - Silver Sponsor 

### ISSUE THREAD

**Issue by andrewgdick** [POWSummit/pow-summit-website#164]
Please add Ballet as a Silver Sponsor 
<img width="1800" alt="Ballet_Logo_Inverse1" src="https://github.com/POWSummit/pow-summit-website/assets/974129/eb6f2b86-635a-43f2-bb13-fd73c3127ff4">
<img width="1800" alt="Ballet_Logo_Inverse2" src="https://github.com/POWSummit/pow-summit-website/assets/974129/b24bf450-d6f0-4644-839e-5b2f66854b46">
<img width="1800" alt="Ballet_Logo_Standard" src="https://github.com/POWSummit/pow-summit-website/assets/974129/7f4819ff-34b1-4310-a134-54beaaaa8631">

**Comment by bobsummerwill** [comment]
Still missing, @gd8097019

**Comment by bobsummerwill** [comment]
Done, thanks!
