### ISSUE TITLE
SEO, card preview and other metadata

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#17]
All of the index.html magic still needs to happen for this website.

**Comment by gd8097019** [comment]
Hi @andrewgdick  I can add html meta tags to project but we need to fill this fields: 

- website url (Exp: https://etcgrantsdao.io)
- Social media card title (Exp: ETC Grants DAO)
- Social media card description (Exp: We provide funding for promising projects that will invigorate the Ethereum Classic ecosystem)
- Social media image jpg or png (Exp: https://etcgrantsdao.io/edg-grants-twitter-card.png)

**Comment by andrewgdick** [comment]
Hey @gd8097019 

website url (Exp: https://powsummit.com/)
Social media card title (Exp: POW Summit)
Social media card description (Exp: Proof of Work Summit - Securing blockchain's future)

Just waiting for the final Twitter Card Image

**Comment by gd8097019** [comment]
@andrewgdick I made html updates. When image is ready I can add to project and create pull request for that.

**Comment by andrewgdick** [comment]
Hey @gd8097019 I have attached the card here. Thanks!
![twitter-card-pow](https://user-images.githubusercontent.com/974129/222907138-87752eae-e266-4bfd-90c2-fc10791a6e2e.png)

**Comment by gd8097019** [comment]
Hey @andrewgdick @bobsummerwill check my PR: https://github.com/POWSummit/pow-summit-website/pull/24

**Comment by bobsummerwill** [comment]
Are we going to need to do this stuff again, @andrewgdick?
Could you check status?
