### ISSUE TITLE
QR Code not working well with Menu Anchor

### ISSUE THREAD

**Issue by andrewgdick** [POWSummit/pow-summit-website#190]
![qrcode](https://github.com/POWSummit/pow-summit-website/assets/974129/3639873f-5c41-4371-ba07-01d130663984)

Hey @gd8097019 Our QR code works intermittently. Do you have any idea why?

Thanks

**Comment by gd8097019** [comment]
I have checked, and it's just a link with scroll to reference. It seems to be working at my end without any issues.
