### ISSUE TITLE
Make the green a hybrid blue/green for the whole page

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#2]
Jav has suggested that we switch the green to be a hybrid blue/green so that we can show our unity.

I am in complete agreement, and would love to see a colouring which is differentiated from the ETC black/green which is becoming rather tedious through repetition.

**Comment by bobsummerwill** [comment]
@belacampello will need to redesign here.

**Comment by belacampello** [comment]
Is this for the whole page?

**Comment by bobsummerwill** [comment]
@belacampello Yes.   It would be for all of the green for the whole page.

**Comment by gd8097019** [comment]
Hi @bobsummerwill and @belacampello I made required CSS updates. See my PR: https://github.com/POWSummit/pow-summit-website/pull/11

Note: Because of my latest PR is still open, css codes goes to inside it.

**Comment by bobsummerwill** [comment]
This was from @belacampello's Figma design?  If so, looks good to me and let's proceed.

**Comment by bobsummerwill** [comment]
>> Note: Because of my latest PR is still open, css codes goes to inside it.

Please can you make per-feature branches on your fork for future PRs, @gd8097019?

There should rarely be a case where you need to intermix the work.

**Comment by bobsummerwill** [comment]
Merged #11

**Comment by gd8097019** [comment]
@bobsummerwill sure it is my mistake. I will try like that next time.
