### ISSUE TITLE
Add Media Page to website

### ISSUE THREAD

**Issue by andrewgdick** [POWSummit/pow-summit-website#209]
Add two separate pages to the website
1) Photo Gallery
2) Video Gallery

Layout
**HEADER with logo then copy:** 
SECURING BLOCKCHAIN'S FUTURE
A cypherpunk-grounded conference that refutes misleading mainstream narratives around proof-of-work and focuses on the fundamentals of this revolutionary freedom technology.

**Gallery** 

**Footer**

The menu structure should be:
MEDIA
- Photos 
- Videos

**Comment by gd8097019** [comment]
Please provide logo, existing website doesn't have logo.
Assuming Media menu will be added after venue.
Also the Gallery photo and video section will be empty at the moment?
