### ISSUE TITLE
Menu issues

### ISSUE THREAD

**Issue by andrewgdick** [POWSummit/pow-summit-website#22]
Menu issues

 "Agenda" is still in the footer menu
The "Sponsor"'s link does not work in the footer menu

Links for Buttons:

Volunteer Form
https://docs.google.com/forms/d/e/1FAIpQLSfMUEsVd5I4TPEPDHbbh0REKSYKA4LGlEstJs0jZxw-lscWMg/viewform

Sponsor Deck
https://docs.google.com/presentation/d/1xnAp2miWbFJpeGCrmXu6ZvuFlYfEpIGd/edit#slide=id.p6

Ticket Page
https://www.eventbrite.ca/e/pow-summit-2023-tickets-551536098317

**Comment by gd8097019** [comment]
Hi @andrewgdick check my PR: https://github.com/POWSummit/pow-summit-website/pull/23
