### ISSUE TITLE
We should not have the ETC+LTC logos in the main title

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#5]
I don't think we should have the ETC+LTC front-and-center in the main title for the website, because that makes it look like this is **onl**y an ETC and LTC conference, which is very much not the case.

I think it's fine to have the ETC Cooperative and LTC Foundation logos in the footer of the site, but we don't want to be pushing that in people's faces as the first thing they see.

Not sure if we need some logo or graphic there instead ... ?

For the ETC+LTC thing in the footer we might want an "organizers" section, like we have for sponsors?   Or maybe that is overkill and we stick with ETC+LTC but just switch out to the correct logo for LTC.   See issue #4

**Comment by gd8097019** [comment]
Hi @bobsummerwill I removed ETC+LTC icons from hero section. 

Note: Mistakenly I made commit to main repository. Next time I will create pull request from my forked repo.

**Comment by bobsummerwill** [comment]
No worries - thanks!
