### ISSUE TITLE
Is it possible to do the circle "cut-out" for the speaker images within the website?

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#6]
At the moment, the circle cut-outs for the speaker images are in the source images, rather than an effect within the website itself.

Is it possible to switch that, so that the cut-out is done within the website itself, with the images being plan and rectangular?

That just makes it easier to manage, because we aren't needing one or more people to know exactly how to generate the images in the right format.   Thanks!

**Comment by bobsummerwill** [comment]
See https://github.com/POWSummit/pow-summit-website/pull/7 as an example with a non-rounded image.

**Comment by gd8097019** [comment]
I made a PR for issue. See: https://github.com/POWSummit/pow-summit-website/pull/8

**Comment by bobsummerwill** [comment]
That has worked great - thank you!
