### ISSUE TITLE
Add Schedule Section

### ISSUE THREAD

**Issue by andrewgdick** [POWSummit/pow-summit-website#69]
The schedule will cover three days and should have:

1) Talk Title  
2) Speaker / Panel info
3) Short Description 
4) Date & Time

**Comment by gd8097019** [comment]
Hey @andrewgdick I created a branch for pow website updates. You can use this branch to edit `config/agenda.json` or you can provide me agenda data to for first time and you can modify it

**Comment by bobsummerwill** [comment]
So we'll be arguing about agenda for a while to come and won't want anything public.

Maybe you can stick this behind a boolean configuration setting in the JSON file, @gd8097019, so we can merge the changes and then keep playing with it and iterating but NOT making that visible to the public?

**Comment by gd8097019** [comment]
Hey @bobsummerwill I binded to agenda `config/agenda.json` in `isAgendaActive` property. You can check this PR: 

https://github.com/POWSummit/pow-summit-website/pull/93

**Comment by bobsummerwill** [comment]
https://docs.google.com/spreadsheets/d/1JIus1IGEzntXGnVUk-aCKwlo0GIGJOETy0-WR0KOPCM/edit?usp=sharing

Please can you update the agenda and enable it as a PR for review?  Thanks!

**Comment by bobsummerwill** [comment]
So have it enabled in the PR.  We can iterate on the PR just a little and go live tomorrow, then tweak the live version as content is finalized. But it is complete enough to go live.

**Comment by bobsummerwill** [comment]
Live now, thanks, @gd8097019
