### ISSUE TITLE
Speakers Section - Background

### ISSUE THREAD

**Issue by andrewgdick** [POWSummit/pow-summit-website#73]
I have received feedback that our speaker section is "boring" 

Maybe a textured background will give it some depth?

Open to suggestions.

**Comment by andrewgdick** [comment]
@gd8097019 can we change the Speakers section into a carousel?

**Comment by gd8097019** [comment]
Hey @andrewgdick could you check my latest PR which contains carousel for speakers

https://github.com/POWSummit/pow-summit-website/pull/98

**Comment by bobsummerwill** [comment]
Carousel in place
