### ISSUE TITLE
Add Social Media Section to Footer

### ISSUE THREAD

**Issue by andrewgdick** [POWSummit/pow-summit-website#76]
Add links to:
- POW Twitter - https://twitter.com/PowSummit
- ETC COOP Twitter - https://twitter.com/ETCCooperative
-  Litecoin Foundation Twitter - https://twitter.com/LTCFoundation
- ETC Coop Linkedin - https://www.linkedin.com/company/etc-cooperative/
- Litecoin Foundation https://www.linkedin.com/company/litecoin-foundation/

**Comment by gd8097019** [comment]
Hey @andrewgdick could you check my PR https://github.com/POWSummit/pow-summit-website/pull/77
